export const WILL_FETCH_PLAYERS = "WILL_FETCH_PLAYERS"
export const SUCCESS_FETCH_PLAYERS = "SUCCESS_FETCH_PLAYERS"
export const ERROR_FETCH_PLAYERS = "ERROR_FETCH_PLAYERS"
export const SET_TOTAL = "SET_TOTAL"
